const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_POSTS_SUCCEEDED = 'FETCH_POSTS_SUCCEEDED';
const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

const CREATE_POST = 'CREATE_POST';   
const FETCH_POST = 'FETCH_POST';
const DELETE_POST = 'DELETE_POST';

export default {
    FETCH_POSTS,
    FETCH_POSTS_SUCCEEDED,
    FETCH_POSTS_FAILED,
    CREATE_POST,
    FETCH_POST,
    DELETE_POST
};
